apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vop.fullname" . }}-api
  labels:
    {{- include "vop.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "vop.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: {{ include "vop.api.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ include "vop.fullname" . }}-config
            - secretRef:
                name: {{ .Values.existingSecret }}
          env:
            - name: VOP_API_PORT
              value: {{ .Values.api.port | quote }}
          livenessProbe:
            httpGet: { path: /api/v1/health/live, port: {{ .Values.api.port }} }
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /api/v1/health/ready, port: {{ .Values.api.port }} }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - { name: tmp, mountPath: /tmp }
      volumes:
        - name: tmp
          emptyDir: {}
