apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vop.fullname" . }}-web
  labels:
    {{- include "vop.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "vop.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: {{ include "vop.web.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.web.port }}
          env:
            - name: PORT
              value: {{ .Values.web.port | quote }}
            - name: HOSTNAME
              value: '0.0.0.0'
            - name: NEXT_PUBLIC_API_URL
              value: {{ printf "https://%s/api/v1" .Values.ingress.host | quote }}
          livenessProbe:
            httpGet: { path: /, port: {{ .Values.web.port }} }
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /, port: {{ .Values.web.port }} }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          volumeMounts:
            - { name: tmp, mountPath: /tmp }
      volumes:
        - name: tmp
          emptyDir: {}
